<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find hector_xacro_tools)/urdf/inertia_tensors.urdf.xacro"/>

  <xacro:macro name="main_track" params="name parent wheel_radius track_width axle_distance *origin">
    <joint name="${name}_fixed_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <xacro:inertial_cuboid_with_pose mass="2.2" x_length="${axle_distance}" y_length="${track_width}" z_length="${wheel_radius*2}">
        <origin xyz="0 0 0 " rpy="0 0 0"/>
      </xacro:inertial_cuboid_with_pose>

      <!-- ==== Visuals ====-->
      <visual>
        <geometry>
          <box size="${axle_distance} ${track_width} ${wheel_radius*2}"/>
        </geometry>
      </visual>

      <!-- Front wheel -->
      <visual>
        <origin xyz="${axle_distance / 2.0} 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${track_width}" radius="${wheel_radius}"/>
        </geometry>
      </visual>

      <!-- Back wheel -->
      <visual>
        <origin xyz="${-axle_distance / 2.0} 0 0" rpy="${pi/2} 0 ${pi}"/>
        <geometry>
          <cylinder length="${track_width}" radius="${wheel_radius}"/>
        </geometry>
      </visual>

      <!-- Tensioned track extension -->
      <visual>
        <origin xyz="${axle_distance / 4.0} 0 ${wheel_radius + 0.005}" rpy="0 ${5*pi/180} 0"/>
        <geometry>
          <box size="${axle_distance / 2} ${track_width} 0.02"/>
        </geometry>
      </visual>

      <visual>
        <origin xyz="${-axle_distance / 4.0} 0 ${wheel_radius + 0.005}" rpy="0 ${-5*pi/180} 0"/>
        <geometry>
          <box size="${axle_distance / 2} ${track_width} 0.02"/>
        </geometry>
      </visual>

      <!-- ==== Collision geom ==== -->
      <!-- Standard track geom -->
      <collision>
        <geometry>
          <box size="${axle_distance} ${track_width} ${wheel_radius*2}"/>
        </geometry>
      </collision>

      <!-- Front wheel -->
      <collision>
        <origin xyz="${axle_distance / 2.0} 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${track_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <!-- Back wheel -->
      <collision>
        <origin xyz="${-axle_distance / 2.0} 0 0" rpy="${pi/2} 0 ${pi}"/>
        <geometry>
          <cylinder length="${track_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <!-- Tensioned track extension -->
      <collision>
        <origin xyz="${axle_distance / 4.0} 0 ${wheel_radius + 0.005}" rpy="0 ${5*pi/180} 0"/>
        <geometry>
          <box size="${axle_distance / 2} ${track_width} 0.02"/>
        </geometry>
      </collision>

      <collision>
        <origin xyz="${-axle_distance / 4.0} 0 ${wheel_radius + 0.005}" rpy="0 ${-5*pi/180} 0"/>
        <geometry>
          <box size="${axle_distance / 2} ${track_width} 0.02"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

</robot>
